### ISSUE TITLE
Example of linking and consuming github packages

### ISSUE THREAD

**Issue by mpetuska** [Heapy/repo.kotlin.link#9]
Hi, I can't figure out how to link and consume github packages. A short guide would be great!

**Comment by IRus** [comment]
Looks like github packages required auth (https://maven.pkg.github.com/mpetuska/npm-publish/lt/petuska/npm-publish/1.1.1/npm-publish-1.1.1.pom)

I generated token (https://github.com/settings/tokens/new):

<img width="807" alt="image" src="https://user-images.githubusercontent.com/493656/107362446-d2b60300-6ae9-11eb-9080-145362802b5a.png">

And use it in maven section:

<img width="483" alt="image" src="https://user-images.githubusercontent.com/493656/107362602-04c76500-6aea-11eb-8eb8-8cb010a422d8.png">

But somehow it doesn't work (but I can use same pair in basic auth in browser https://maven.pkg.github.com/mpetuska/npm-publish/lt/petuska/npm-publish/1.1.1/npm-publish-1.1.1.pom).

**Comment by IRus** [comment]
With repo itself, no problems: https://maven.pkg.github.com/mpetuska/npm-publish/

**Comment by IRus** [comment]
But even without proxy repo I can't pull from https://maven.pkg.github.com/mpetuska/khakra
Is it "public"?

**Comment by mpetuska** [comment]
it is, and I'm able to pull from it directly

**Comment by mpetuska** [comment]
```kotlin
repositories {
  maven("https://maven.pkg.github.com/mpetuska/khakra") {
    credentials {
      username = project.properties["gpr.username"]?.toString() ?: System.getenv("GH_PKG_USER")
      password = project.properties["gpr.password"]?.toString() ?: System.getenv("GH_PKG_PASSWORD")
    }
  }
}
```

**Comment by IRus** [comment]
Hmm, I need more time to investigate, will do this evening

**Comment by mpetuska** [comment]
Any progress on this? Might be good to setup some github service user credentials to expose gh packages anonymously via this project?

**Comment by IRus** [comment]
What happens normally:

```
Gradle -> HEAD maven.pkg.github.com
  Github -> 401, www-authenticate: Basic realm="GitHub Package Registry"
Gradle -> HEAD maven.pkg.github.com, Authorization: Basic <credentials>
```

What happens with http redirect:
```
Gradle -> HEAD repo.kotlin.link
  repo.kotlin.link -> 302, maven.pkg.github.com
Gradle -> HEAD, maven.pkg.github.com
  Github -> 401, www-authenticate: Basic realm="GitHub Package Registry"
    Gradle -> Fail
```

I don't know why client doesn't try to do auth for redirected location, and just fails instead.
It's maybe bug in client used in gradle, or behavior according spec.

**Comment by mpetuska** [comment]
Ah, but you need to redirect to `https://maven.pkg.github.com/mpetuska/khakra` (note the subpath). I think `https://repo.kotlin.link/mpetuska/khakra` might just work. Ideally you'd support path segments in sub-repos for redirection, not just domain

**Comment by IRus** [comment]
Yes, location taken into account, I exclude it from explanation to reduce noise:

<img width="547" alt="image" src="https://user-images.githubusercontent.com/493656/107849044-8f210900-6e09-11eb-943f-0479c9945836.png">

**Comment by IRus** [comment]
So conclusion is: 
1. Repositories required authentication doesn't work
2. Even if they'll work, it's security risk, since basic auth (essentially open user + token) can be sent to 3rd party repo by gradle

**Comment by mpetuska** [comment]
I think github is the main draw to this project. Even if it'd just proxy the auth from the consumer

**Comment by IRus** [comment]
Yes, github probably is huge source of packages, but currently it not possible to support it. I thinking about organizing enterprise level repository on top of ipfs, but right now it's just idea
